### ISSUE TITLE
android4.2  libcurl  cannot locate symbol "EVP_MD_CTX_free"

### ISSUE THREAD

**Issue by luhuajcdd** [curl/curl#10247]
### I did this
Reference compilation：
https://github.com/F3FFO/compile_zlib_openssl_curl_android
export MIN_SDK_VERSION=17
export NDK_ROOT=/home/hua/Android/Sdk/ndk/22.1.7171670

armeabi-v7a and x86   so: 
libcrypto.so
libssl.so
libcurl.so

```
System.loadLibrary("crypto");
System.loadLibrary("ssl");
System.loadLibrary("curl");
```
so download url: 
https://pan.baidu.com/s/14nT9aHMcPIevZstnL3QRhQ   code：546t

D/dalvikvm(31934): VFY: replacing opcode 0x6e at 0x0011
D/dalvikvm(31934): Trying to load lib /data/app-lib/com.san.android_ios-1/libssl.so 0x4139f660
D/dalvikvm(31934): Added shared lib /data/app-lib/com.san.android_ios-1/libssl.so 0x4139f660
D/dalvikvm(31934): No JNI_OnLoad found in /data/app-lib/com.san.android_ios-1/libssl.so 0x4139f660, skipping init
D/dalvikvm(31934): Trying to load lib /data/app-lib/com.san.android_ios-1/libcrypto.so 0x4139f660
D/dalvikvm(31934): Added shared lib /data/app-lib/com.san.android_ios-1/libcrypto.so 0x4139f660
D/dalvikvm(31934): No JNI_OnLoad found in /data/app-lib/com.san.android_ios-1/libcrypto.so 0x4139f660, skipping init
D/dalvikvm(31934): Trying to load lib /data/app-lib/com.san.android_ios-1/libcurl.so 0x4139f660
### E/dalvikvm(31934): dlopen("/data/app-lib/com.san.android_ios-1/libcurl.so") failed: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "EVP_MD_CTX_free" referenced by "libcurl.so"...
W/dalvikvm(31934): method Lio/flutter/embedding/android/FlutterView;.findViewByAccessibilityIdTraversal incorrectly overrides package-private method with same name in Landroid/view/ViewGroup;
W/dalvikvm(31934): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)

EVP_MD_CTX_free in libcrypto.so 
ubuntu@ubuntucompile_zlib_openssl_curl_android-master$ readelf -s build/openssl/armeabi-v7a/lib/libcrypto.so | grep EVP_MD_CTX_free
  2253: 00199a0c    56 FUNC    GLOBAL DEFAULT   14 EVP_MD_CTX_free@@OPENSSL_3.0.0
 21703: 00199a0c    56 FUNC    GLOBAL DEFAULT   14 EVP_MD_CTX_free
ubuntu@ubuntucompile_zlib_openssl_curl_android-master$ readelf -s build/openssl/armeabi-v7a/lib/libssl.so | grep EVP_MD_CTX_free
    57: 00000000     0 FUNC    GLOBAL DEFAULT  UND EVP_MD_CTX_free@OPENSSL_3.0.0 (4)
  3631: 00000000     0 FUNC    GLOBAL DEFAULT  UND EVP_MD_CTX_free
ubuntu@ubuntucompile_zlib_openssl_curl_android-master$ readelf -s build/curl/armeabi-v7a/lib/libcurl.so | grep EVP_MD_CTX_free
   103: 00000000     0 FUNC    GLOBAL DEFAULT  UND EVP_MD_CTX_free@OPENSSL_3.0.0 (3)
  2933: 00000000     0 FUNC    GLOBAL DEFAULT  UND EVP_MD_CTX_free

### I expected the following

load libcurl.so successful

### curl/libcurl version
7.86.0

openssl: 3.0.7

[curl -V output]

### operating system
android 4.2

**Comment by bagder** [comment]
I don't see how this is a curl problem.

- This is not a problem in any of the CI jobs we run. Now or in the past.
- `EVP_MD_CTX_free` is not used directly by curl code 
- In my static curl builds on Linux I find the `EVP_MD_CTX_free` symbol fine (`nm src/curl | grep EVP_MD_CTX_free`)
- In my local openSSL 3.0.7 .so files the  `EVP_MD_CTX_free`  symbol is present

To me, this looks like a problem in the build/setup/environment.

I have never personally built curl for Android.

**Comment by jay** [comment]
> To me, this looks like a problem in the build/setup/environment.

Probably libcurl was built against OpenSSL 3.0.0 from one location and the application has loaded a build of OpenSSL from a different location and might be a different version.

**Comment by luhuajcdd** [comment]
> > To me, this looks like a problem in the build/setup/environment.
> 
> Probably libcurl was built against OpenSSL 3.0.0 from one location and the application has loaded a build of OpenSSL from a different location and might be a different version.


I try to create a new android application.  load 3 lib(libcrypto.so libssl.so libcurl.so) only.  get same errorrs: 
W/dalvikvm(31748): threadid=1: thread exiting with uncaught exception (group=0x40dbe930)
I/InputDispatcher(  706): Dropping event because there is no touched window.
E/AndroidRuntime(31748): FATAL EXCEPTION: main
E/AndroidRuntime(31748): java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "EVP_MD_CTX_free" referenced by "libcurl.so"...
E/AndroidRuntime(31748):        at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(31748):        at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime(31748):        at com.example.android_demo.MainActivity.onCreate(MainActivity.java:32)
E/AndroidRuntime(31748):        at android.app.Activity.performCreate(Activity.java:5113)
E/AndroidRuntime(31748):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime(31748):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime(31748):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime(31748):        at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime(31748):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime(31748):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31748):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(31748):        at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(31748):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31748):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(31748):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(31748):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(31748):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  706):   Force finishing activity com.example.android_demo/.MainActivity

**Comment by bagder** [comment]
Sure, you get a problem but we can't see how this is curl's fault.
