### ISSUE TITLE
RTSP assert in OSS-fuzz:  ASSERT · blen == 0 || data->req.header 

### ISSUE THREAD

**Issue by bagder** [curl/curl#12738]
### I did this

~~~
 Last Tested Stacktrace on revision 48aaab55a58c100c8c289a55dbeda5e2099592e5 (49 lines)
	+----------------------------------------Release Build Stacktrace----------------------------------------+
	Command: /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp
	Time ran: 0.0540158748626709
	
	Accepting input from '[STDIN]'
	Usage for fuzzing: honggfuzz -P [flags] -- /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp
	curl_fuzzer_rtsp: rtsp.c:807: CURLcode rtsp_rtp_write_resp(struct Curl_easy *, const char *, size_t, _Bool, _Bool *): Assertion `blen == 0 || data->req.header' failed.
	AddressSanitizer:DEADLYSIGNAL
	=================================================================
	==402==ERROR: AddressSanitizer: ABRT on unknown address 0x053900000192 (pc 0x7800e82dd00b bp 0x7800e8452588 sp 0x7ffd18121d90 T0)
	SCARINESS: 10 (signal)
	    #0 0x7800e82dd00b in raise /build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
	    #1 0x7800e82bc858 in abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79:7
	    #2 0x7800e82bc728 in __assert_fail_base /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:92:3
	    #3 0x7800e82cdfd5 in __assert_fail /build/glibc-SzIz7B/glibc-2.31/assert/assert.c:101:3
	    #4 0x65233a in rtsp_rtp_write_resp curl/lib/rtsp.c:807:5
	    #5 0x54f8c8 in Curl_xfer_write_resp curl/lib/transfer.c:1686:14
	    #6 0x54f8c8 in readwrite_data curl/lib/transfer.c:533:14
	    #7 0x54f8c8 in Curl_readwrite curl/lib/transfer.c:920:14
	    #8 0x516fc9 in multi_runsingle curl/lib/multi.c:2483:16
	    #9 0x514897 in curl_multi_perform curl/lib/multi.c:2780:16
	    #10 0x4def86 in fuzz_handle_transfer(fuzz_data*) curl_fuzzer/curl_fuzzer.cc:419:5
	    #11 0x4ddef9 in LLVMFuzzerTestOneInput curl_fuzzer/curl_fuzzer.cc:97:3
	    #12 0xf9e70b in main
	    #13 0x7800e82be082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
	    #14 0x41f0dd in _start
	
	AddressSanitizer can not provide additional info.
	SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	==402==ABORTING
	
	
	+----------------------------------------Release Build Unsymbolized Stacktrace (diff)----------------------------------------+
	
	==402==ERROR: AddressSanitizer: ABRT on unknown address 0x053900000192 (pc 0x7800e82dd00b bp 0x7800e8452588 sp 0x7ffd18121d90 T0)
	SCARINESS: 10 (signal)
	    #0 0x7800e82dd00b  (/lib/x86_64-linux-gnu/libc.so.6+0x4300b) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	    #1 0x7800e82bc858  (/lib/x86_64-linux-gnu/libc.so.6+0x22858) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	    #2 0x7800e82bc728  (/lib/x86_64-linux-gnu/libc.so.6+0x22728) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	    #3 0x7800e82cdfd5  (/lib/x86_64-linux-gnu/libc.so.6+0x33fd5) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	    #4 0x65233a  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x65233a)
	    #5 0x54f8c8  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x54f8c8)
	    #6 0x516fc9  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x516fc9)
	    #7 0x514897  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x514897)
	    #8 0x4def86  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x4def86)
	    #9 0x4ddef9  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x4ddef9)
	    #10 0xf9e70b  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0xf9e70b)
	    #11 0x7800e82be082  (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
	    #12 0x41f0dd  (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-honggfuzz_curl_d1a7f12cc2e5055727a9c66d5eca203f3c8f5a6c/revisions/curl_fuzzer_rtsp+0x41f0dd)
~~~

### curl/libcurl version

It identifies this is the regression range: https://github.com/curl/curl/compare/5da57193b732687f430e75f82e16d71835f9dbf3...d7b6ce64ce0ad787ad2ed3ee05c94938a6b4f551

### operating system

any

**Comment by icing** [comment]
#12739 should fix this.
