### ISSUE TITLE
curl crashed in ConnectionExists?

### ISSUE THREAD

**Issue by bethebest0622** [curl/curl#13025]
### I did this

I use curl to do get/post/delete request 

```
#0  0x00007f4249b80717 in ConnectionExists () from /usr/lib64/libcurl.so.4
#1  0x00007f4249be2238 in Curl_connect () from /usr/lib64/libcurl.so.4
#2  0x00007f4249bbf3db in multi_runsingle () from /usr/lib64/libcurl.so.4
#3  0x00007f4249bc0792 in curl_multi_perform () from /usr/lib64/libcurl.so.4
#4  0x00007f4249b96e5b in curl_easy_perform () from /usr/lib64/libcurl.so.4
#5  0x00007f424bc05f1c in util::curl_util::CurlClient::execute(void*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, curl_slist*) () from /usr/local/lib/libcurl_util.so
#6  0x00007f424bc0688d in util::curl_util::CurlClient::common_push(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/local/lib/libcurl_util.so
#7  0x00007f424bc06a68 in util::curl_util::CurlClient::Delete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/local/lib/libcurl_util.so
#8  0x00007f42451a3c06 in crypto::adapter::BinanceUnion::cancel_order(lws*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}::operator()() const () from crypto_libs/libtrade_binance_union.so
#9  0x00007f42451a42ae in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<crypto::adapter::BinanceUnion::cancel_order(lws*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1} ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) () from crypto_libs/libtrade_binance_union.so
#10 0x00007f42451a6d6b in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) ()
   from crypto_libs/libtrade_binance_union.so
#11 0x00007f424b93ce97 in __pthread_once_slow () from /usr/lib64/libpthread.so.0
#12 0x00007f424519b242 in std::__future_base::_Task_state<std::_Bind<crypto::adapter::BinanceUnion::cancel_order(lws*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1} ()>, std::allocator<int>, void ()>::_M_run() () from crypto_libs/libtrade_binance_union.so
#13 0x00007f42451a703e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run() () from crypto_libs/libtrade_binance_union.so
#14 0x00007f424b4b3b23 in execute_native_thread_routine () from /usr/lib64/libstdc++.so.6
#15 0x00007f424b9351ca in start_thread () from /usr/lib64/libpthread.so.0
#16 0x00007f424aaba8d3 in clone () from /usr/lib64/libc.so.6
```

### I expected the following

I expected it can run well

### curl/libcurl version

curl 8.2.1 from yum repo cityfan

### operating system

centos 8 stream

**Comment by dfandrich** [comment]
This is a threaded application. Is the code following all the recommendations at https://curl.se/libcurl/c/threadsafe.html?

**Comment by bagder** [comment]
No response
