### ISSUE TITLE
enable c-ares with segmentation fault

### ISSUE THREAD

**Issue by EGeeks** [curl/curl#15375]
### I did this

	while (p_http->is_thread_running) {
		int still_running = 0;

		CURLMcode mc = curl_multi_perform(p_http->multi, &still_running);
		if (still_running) {
			mc = curl_multi_poll(p_http->multi, NULL, 0, 1000, NULL);
		}
		if (mc)
			continue;

		while ((msg = curl_multi_info_read(p_http->multi, &msgs_in_queue))) {
			if (msg->msg == CURLMSG_DONE) {
				CURL *easy_handle = msg->easy_handle;

				//				if (msg->data.result != CURLE_OK) {
				//					char *done_url;
				//					curl_easy_getinfo(easy_handle, CURLINFO_EFFECTIVE_URL, &done_url);
				//					mw_debug("url=%s, result=%d\n", done_url, msg->data.result);
				//				}

				curl_multi_remove_handle(p_http->multi, easy_handle);
				curl_easy_cleanup(easy_handle);
			} else {
				mw_debug("unsupport CURLMsg (%d)\n", msg->msg);
			}
		}

		sleep_ms(1);
	}

### I expected the following

~~~
#0  Curl_splay (i=..., t=0x7f781b2d20) at ../../curl-8.10.1/lib/splay.c:75
        comp = <optimized out>
        N = {smaller = 0x0, larger = 0x0, samen = 0x7f8bdde500, samep = 0x7f8d2be434 <multi_runsingle+484>, key = {tv_sec = 547807421536, tv_usec = -1926436796}, ptr = 0x7f8bdde4b0}
        l = 0x7f8bdde430
        r = 0x7f8bdde430
        y = 0x0
#1  0x0000007f8d2cde68 in Curl_splayinsert (i=..., t=<optimized out>, node=node@entry=0x7f7821e420) at ../../curl-8.10.1/lib/splay.c:113
No locals.
#2  0x0000007f8d2bcb1c in Curl_expire_ex (data=data@entry=0x7f7821d6f0, nowp=nowp@entry=0x7f8bdde588, milli=milli@entry=10000, id=id@entry=EXPIRE_TIMEOUT) at ../../curl-8.10.1/lib/multi.c:3626
        multi = 0x55ab33bcc0
        curr_expire = 0x7f7821e410
        set = {tv_sec = 17119, tv_usec = 945540}
#3  0x0000007f8d2bf078 in Curl_expire (id=EXPIRE_TIMEOUT, milli=10000, data=0x7f7821d6f0) at ../../curl-8.10.1/lib/multi.c:3633
        now = {tv_sec = 17109, tv_usec = 945540}
#4  multi_runsingle (multi=multi@entry=0x55ab33bcc0, nowp=nowp@entry=0x7f8bdde648, data=data@entry=0x7f7821d6f0) at ../../curl-8.10.1/lib/multi.c:1887
        stream_error = false
        msg = 0x0
        connected = 139
        async = true
        protocol_connected = false
        dophase_done = false
        rc = CURLM_OK
        result = CURLE_OK
        recv_timeout_ms = <optimized out>
        send_timeout_ms = <optimized out>
        control = 127
#5  0x0000007f8d2c06f0 in curl_multi_perform (multi=0x55ab33bcc0, running_handles=running_handles@entry=0x7f8bdde7e4) at ../../curl-8.10.1/lib/multi.c:2653
        data = 0x7f7821d6f0
        result = <optimized out>
        returncode = CURLM_OK
        t = 0x0
        now = {tv_sec = 17109, tv_usec = 945540}
        e = <optimized out>
        n = 0x7f78226d30
        pipe_st = {old_pipe_act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}, no_signal = true}
#6  0x0000005570d0f914 in _thread_cb (p_thread=0x5570e09d70 <g_app+31560>, arg=0x5570e09d68 <g_app+31552>)
    at /usr/src/debug/mw-route-interdev/git-AUTOINC+29431d9415-r0/git/dep/mw_aiohttp/src/aiohttp.c:42
        still_running = 8
        mc = <optimized out>
        p_http = 0x5570e09d68 <g_app+31552>
        msg = <optimized out>
        msgs_in_queue = 0
        __func__ = "_thread_cb"
#7  0x0000005570d0b134 in thread_proc_wrapper (parameter=0x5570e09d70 <g_app+31560>) at /usr/src/debug/mw-base/git-AUTOINC+a1c376f00d-r0/git/src/posix/thread.c:62
        p_thread = 0x5570e09d70 <g_app+31560>
        p_impl = 0x55ab340170
        ret = 0
        prio = <optimized out>
#8  0x0000007f8ceef788 in start_thread (arg=0x7ff8bfded6) at pthread_create.c:442
        ret = <optimized out>
        pd = 0x7ff8bfded6
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {547807424768, 549634170584, 549634170582, 549634170583, 0, 0, 547807424768, 547798974464, 0, 547807424768, 547807422512, 989255810235104764, 0, 
                989255810322194488, 0, 0, 0, 0, 0, 0, 0, 0}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x0000007f8cf560dc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
No locals.
~~~

### curl/libcurl version

curl 8.10

### operating system

linux

**Comment by dfandrich** [comment]
Does this libcurl application take into account all the points mentioned in https://curl.se/libcurl/c/threadsafe.html?

**Comment by bagder** [comment]
Please tell us how to reproduce this.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bagder** [comment]
No response
