### ISSUE TITLE
Slow ssl handshake when certificate contains many subjectAltName dns records

### ISSUE THREAD

**Issue by polonskiy** [curl/curl#3635]
### I did this
Certificate contains 1000 dns records in subjectAltName. 
```
$ curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt https://host1.foo.test:8080/
0.105
$ curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt https://host100.foo.test:8080/
1.234
$ curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt https://host250.foo.test:8080/
2.900
$ curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt https://host500.foo.test:8080/
5.809
$ curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt https://host1000.foo.test:8080/
11.956
```

### I expected the following
I did not expect such slowdown.

### curl/libcurl version
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

### operating system
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

### test setup
Certificate generator:
```
#!/bin/bash

san=$(seq 1000 | sed 's|.*|DNS:host\0.foo.test|' | paste -d, -s)

openssl req \
    -x509 \
    -newkey rsa:4096 \
    -days 3650 \
    -nodes \
    -subj "/CN=testca" \
    -keyout testca.key \
    -out testca.crt
openssl req \
    -newkey rsa:2048 \
    -sha256 \
    -nodes \
    -keyout test.key \
    -out test.csr \
    -subj "/CN=test"
openssl x509 \
    -req \
    -days 3650 \
    -CA testca.crt \
    -CAkey testca.key \
    -CAcreateserial \
    -in test.csr \
    -out test.crt \
    -extfile <(echo "subjectAltName=$san")
```

`nginx.conf`:
```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
	worker_connections  1024;
}


http {
	include       /etc/nginx/mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
					  '$status $body_bytes_sent "$http_referer" '
					  '"$http_user_agent" "$http_x_forwarded_for"';

	access_log  /var/log/nginx/access.log  main;

	server {
		listen 443 ssl default_server;
		server_name .foo.test;
		ssl_certificate /etc/nginx/test.crt;
		ssl_certificate_key /etc/nginx/test.key;

		location / {
			default_type text/plain;
			return 200 "$request_id $time_iso8601\n";
		}

	}

}
```

`docker exec ssltest nginx -V`
```
nginx version: nginx/1.15.6
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.15.6/debian/debuild-base/nginx-1.15.6=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```

**Comment by polonskiy** [comment]
wget for comparison:
```
$ time wget -q -O /dev/null --ca-certificate testca.crt https://host1.foo.test:8080/

real	0m0.014s
user	0m0.010s
sys	0m0.000s
```
```
$ time wget -q -O /dev/null --ca-certificate testca.crt https://host1000.foo.test:8080/

real	0m0.010s
user	0m0.008s
sys	0m0.000s
```

**Comment by bagder** [comment]
I cannot reproduce with current dev version on my machine. Thanks for the awesome recipe that made it dead easy to fire up a local copy to test against:

    $ ./src/curl -V | grep Gnu
    curl 7.64.1-DEV (x86_64-pc-linux-gnu) libcurl/7.64.1-DEV GnuTLS/3.6.6 zlib/1.2.11 brotli/1.0.7 c-ares/1.14.0 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) nghttp2/1.36.0 librtmp/2.3

Running my debug version of the build, this takes a little longer than a real build but it still easily completes within a hundred milliseconds:

    $ time ./src/curl https://localhost:8443/ -vk 2>/dev/null
    real    0m0.062s
    user    0m0.056s
    sys     0m0.001s

The Debian (unstable) packaged curl version (7.64.0) on my machine (using OpenSSL) does the same in 17 milliseconds. wget 1.21.1 on the same machine, also the Debian version, takes 55  milliseconds.

**Comment by bagder** [comment]
Unless someone can reproduce this with a recent version of curl and GnuTLS I will assume that this issue is fixed.

**Comment by polonskiy** [comment]
I guess the slowest part is subjectAltName & domain matching. You are using insecure flag and testing localhost only - it is not the case.

**Comment by polonskiy** [comment]
I'll try  to test newer curl versions little bit later.

**Comment by bagder** [comment]
It actually doesn't make any notable difference in my tests:

    $ time ./src/curl https://host1000.foo.test:8443/ --cacert debug/testca.crt -v --resolve host1000.foo.test:8443:127.0.0.1
    real    0m0.055s

**Comment by polonskiy** [comment]
Seems like version(distro?)-specific issue (Ubuntu 16.04.4 + curl 7.47.0)
I've done some tests:
```
Debian GNU/Linux 7 (wheezy)
curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1t zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
time_appconnect: 0.004

Debian GNU/Linux 8 (jessie)
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP 
time_appconnect: 0.004

Debian GNU/Linux 9 (stretch)
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2r zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
time_appconnect: 0.007208

Debian GNU/Linux buster/sid
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
time_appconnect: 0.002760
```

```
Ubuntu 14.04.5 LTS
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
time_appconnect: 0.006

Ubuntu 16.04.4 LTS
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
time_appconnect: 12.322

Ubuntu 18.04.1 LTS
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
time_appconnect: 0.008122

Ubuntu 18.10
curl 7.61.0 (x86_64-pc-linux-gnu) libcurl/7.61.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) nghttp2/1.32.1 librtmp/2.3
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
time_appconnect: 0.002646

Ubuntu Disco Dingo (development branch)
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
time_appconnect: 0.002536
```

**Comment by bagder** [comment]
Nice list of tests there!

Out of all those tests, only one was built to use GnuTLS though.

**Comment by dfandrich** [comment]
I see an obvious discrepancy in that list: the only slow one is using GnuTLS.

**Comment by jay** [comment]
I can reproduce using the version of curl packaged with Ubuntu 16. 

`perf record /usr/bin/curl -w "%{time_appconnect}\n" -s -o /dev/null --cacert testca.crt --resolve "host1000.foo.test:443:127.0.0.1" https://host1000.foo.test:443/`

and `perf report -f`
~~~
  71.27%  curl     libtasn1.so.6.5.1    [.] asn1_find_node
   4.69%  curl     libc-2.23.so         [.] _int_malloc
   3.75%  curl     libc-2.23.so         [.] _int_free
   2.87%  curl     libc-2.23.so         [.] __libc_calloc
   1.54%  curl     libtasn1.so.6.5.1    [.] asn1_delete_structure2
   1.36%  curl     libc-2.23.so         [.] __memset_sse2
   0.81%  curl     libc-2.23.so         [.] free
   0.68%  curl     libc-2.23.so         [.] __memcpy_sse2_unaligned
   0.63%  curl     libc-2.23.so         [.] strlen
   0.63%  curl     libtasn1.so.6.5.1    [.] asn1_der_decoding2
   0.51%  curl     libc-2.23.so         [.] __GI_____strtoull_l_internal
~~~

and stack from an induced sigint

~~~
(gdb) bt
#0  0x00007ffff59eadf0 in asn1_find_node ()
   from /usr/lib/x86_64-linux-gnu/libtasn1.so.6
#1  0x00007ffff59ea43f in asn1_read_value_type ()
   from /usr/lib/x86_64-linux-gnu/libtasn1.so.6
#2  0x00007ffff6a4cb8f in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#3  0x00007ffff6a579f7 in gnutls_x509_ext_import_subject_alt_names ()
   from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#4  0x00007ffff6a4aecb in ?? () from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#5  0x00007ffff6a4d11f in gnutls_x509_crt_get_subject_alt_name ()
   from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#6  0x00007ffff6a4789a in gnutls_x509_crt_check_hostname2 ()
   from /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#7  0x00007ffff7bba65d in gtls_connect_step3 (conn=conn@entry=0x5555557b65f0, 
    sockindex=sockindex@entry=0) at vtls/gtls.c:1075
#8  0x00007ffff7bbb48a in gtls_connect_common (conn=0x5555557b65f0, 
    sockindex=<optimized out>, nonblocking=<optimized out>, 
    done=0x7fffffffdef9) at vtls/gtls.c:1333
#9  0x00007ffff7bbc1b0 in Curl_ssl_connect_nonblocking (
    conn=conn@entry=0x5555557b65f0, sockindex=sockindex@entry=0, 
    done=0x7fffffffdef9) at vtls/vtls.c:333
#10 0x00007ffff7b7940e in https_connecting (conn=0x5555557b65f0, 
    done=<optimized out>) at http.c:1386
#11 0x00007ffff7b9eef6 in multi_runsingle (multi=multi@entry=0x5555557acf40, 
---Type <return> to continue, or q <return> to quit---
~~~

Since we only call `gnutls_x509_crt_check_hostname` once this doesn't appear to be a curl issue.

**Comment by bagder** [comment]
Thanks for those awesome details @jay!

I think all this is evidence enough to suggest that the problem as reported here is due to GnuTLS in Ubuntu 16 being slow. It seems later GnuTLS versions don't have this problem and curl built to use OpenSSL does not show this slowness.

We therefor recommend you either upgrade your GnuTLS library or switch to a libcurl built against another TLS library.

This is not a curl bug.

**Comment by polonskiy** [comment]
Thanks!
