### ISSUE TITLE
urlapi: memory leak possibly introduced by c6f250c4d6a89

### ISSUE THREAD

**Issue by pauldreik** [curl/curl#4456]
The http fuzzer found a memory leak during redirects. The sanitizer output is shown below.

The problematic input  (fuzzer tlv encoded) is 
```
paul@tonfisk:~/code/delaktig/curl/build-fuzz-clang7-asan-ubsan$ hd blaha 
00000000  00 01 00 00 00 1d 68 74  74 70 3a 2f ff ff ff ff  |......http:/....|
00000010  ff ff ff ff ff ff ff ff  ff ff ff 3f 20 20 20 20  |...........?    |
00000020  20 20 20 00 02 00 00 00  d5 48 54 54 50 2f 31 2e  |   ......HTTP/1.|
00000030  31 20 34 30 31 20 20 20  20 20 20 20 20 20 20 20  |1 401           |
00000040  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
00000050  20 20 20 20 20 20 0a 57  57 57 2d 41 75 74 68 65  |      .WWW-Authe|
00000060  6e 74 69 63 61 74 65 3a  20 44 69 67 65 73 74 20  |nticate: Digest |
00000070  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
00000090  20 20 20 20 20 20 3d 20  20 20 20 20 20 20 2c 20  |      =       , |
000000a0  6e 6f 6e 63 65 3d 20 20  20 20 20 20 20 20 20 20  |nonce=          |
000000b0  20 20 20 20 20 20 20 20  20 20 20 20 20 20 20 20  |                |
*
000000e0  20 0a 0d 20 20 20 20 20  20 20 20 20 20 20 20 20  | ..             |
000000f0  20 20 20 20 20 20 20 20  20 20 20 20 20 0a 00 03  |             ...|
00000100  00 00 00 05 20 20 20 20  20 00 10 00 00 00 04 20  |....     ...... |
00000110  20 20 ff                                          |  .|
00000113
```
In case you want to work with it, here it is in base64:
```
AAEAAAAdaHR0cDov////////////////////PyAgICAgICAAAgAAANVIVFRQLzEuMSA0MDEgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKV1dXLUF1dGhlbnRpY2F0ZTogRGlnZXN0ICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPSAgICAgICAsIG5vbmNlPSAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCg0g
ICAgICAgICAgICAgICAgICAgICAgICAgIAoAAwAAAAUgICAgIAAQAAAABCAgIP8=
```

The sanitizer output:

```
paul@tonfisk:~/code/delaktig/curl/build-fuzz-clang7-asan-ubsan$ tests/curl_fuzzer_http blaha 
INFO: Seed: 4096588511
INFO: Loaded 1 modules   (319537 inline 8-bit counters): 319537 [0x24af620, 0x24fd651), 
INFO: Loaded 1 PC tables (319537 PCs): 319537 [0x1898628,0x1d78938), 
tests/curl_fuzzer_http: Running 1 inputs 1 time(s) each.
Running: blaha

=================================================================
==30232==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x567827 in __interceptor_malloc (/home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/tests/curl_fuzzer_http+0x567827)
    #1 0x5ce425 in curl_dbg_malloc /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/memdebug.c:174:9
    #2 0xc041af in seturl /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/urlapi.c:856:18
    #3 0xbf9d70 in parseurl /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/urlapi.c:951:22
    #4 0xbf5b61 in curl_url_set /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/urlapi.c:1325:16
    #5 0xa5dd9a in Curl_follow /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/transfer.c:1593:8
    #6 0x63400b in multi_runsingle /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/multi.c:2042:20
    #7 0x62034a in curl_multi_perform /home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/../lib/multi.c:2226:14
    #8 0x5b1947 in fuzz_handle_transfer(FUZZ_DATA*) /home/paul/code/delaktig/curl-fuzzer/intree_fuzzer/src/networkfuzzers/curl_fuzzer.cc:288:5
    #9 0x5ae0f4 in LLVMFuzzerTestOneInput /home/paul/code/delaktig/curl-fuzzer/intree_fuzzer/src/networkfuzzers/curl_fuzzer.cc:112:3
    #10 0x47a40d in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/tests/curl_fuzzer_http+0x47a40d)
    #11 0x469e7a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/tests/curl_fuzzer_http+0x469e7a)
    #12 0x474db8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/tests/curl_fuzzer_http+0x474db8)
    #13 0x466ae2 in main (/home/paul/code/delaktig/curl/build-fuzz-clang7-asan-ubsan/tests/curl_fuzzer_http+0x466ae2)
    #14 0x7f4e1a88db96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

```

If I revert c6f250c4d6a8964a24d99aaf0e0cb81ab9cb293f, this test case does not reproduce anymore. That does not prove c6f250c4d6a8964a24d99aaf0e0cb81ab9cb293f is the culprit, it may expose a bug not possible to trigger earlier.

I report this as a bug since it is a leak and seems to have been introduced very recently.

**Comment by bagder** [comment]
I believe #4453 will fix this one

**Comment by bagder** [comment]
#4453 is merged now. Can you still repro?

**Comment by pauldreik** [comment]
Nice, that fixes it! Thanks
