### ISSUE TITLE
mime.c memory leak

### ISSUE THREAD

**Issue by bagder** [curl/curl#4781]
And `$ echo "LUY9CnVyIDA=" | base64 -d > test0061.conf && ./curl -q -K test0061.conf file:///dev/null` produces this leak in mime.c:
```
curl: (7) Failed to connect to 0 port 80: Connection refused

=================================================================
==2511==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 448 byte(s) in 1 object(s) allocated from:
    #0 0x49451d in malloc (/root/curl/build2-afl/src/curl+0x49451d)
    #1 0x6c51eb in curl_mime_addpart /root/curl/build2-afl/lib/../../lib/mime.c:1252:28

Indirect leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x49451d in malloc (/root/curl/build2-afl/src/curl+0x49451d)
    #1 0x6c4e6c in curl_mime_init /root/curl/build2-afl/lib/../../lib/mime.c:1215:24

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x49451d in malloc (/root/curl/build2-afl/src/curl+0x49451d)
    #1 0x6c353b in curl_mime_data /root/curl/build2-afl/lib/../../lib/mime.c:1318:18

SUMMARY: AddressSanitizer: 553 byte(s) leaked in 3 allocation(s).
```

_Originally posted by @geeknik in https://github.com/curl/curl/issues/4772#issuecomment-569961494_

**Comment by bagder** [comment]
I can reproduce.
