### ISSUE TITLE
Segfault with static build of 7.77.0 and 7.77.1-dev (using llvm 12)

### ISSUE THREAD

**Issue by satmandu** [curl/curl#7194]
### I did this
curl was built from HEAD usng this:
```
env CC=clang CXX=clang++ LD=ld.lld RANLIB=llvm-ranlib \
      AR=llvm-ar \
      CFLAGS='-flto -pipe -O3 -fuse-ld=lld' \
      CXXFLAGS='-flto -pipe -O3' \
      LDFLAGS='-flto -static -Wl,--no-as-needed -ldl' \
      LIBS='-l:libkrb5support.a -l:libgssapi_krb5.a -l:libkrb5.a -l:libk5crypto.a -l:libcom_err.a -l:libzstd.a  \
      -lm -l:libbrotlicommon.a -l:libbrotlidec.a -l:libunistring.a \
      -l:libidn2.a -lz -lssl -lcrypto \
      -l:libsasl2.a -l:libxml2.a -lpthread' \
      ./configure --prefix=/usr/local --libdir=/usr/local/lib64 \
      --disable-ldap \
      --disable-libcurl-option \
      --disable-maintainer-mode \
      --disable-shared \
      --enable-ipv6 \
      --enable-debug \
      --enable-static \
      --enable-unix-sockets \
      --with-ca-bundle=/usr/local/etc/ssl/certs/ca-certificates.crt \
      --with-ca-fallback \
      --with-ca-path=/usr/local/etc/ssl/certs \
      --with-libidn2 \
      --with-openssl\
      --without-librtmp"
```
### I did this:
```
curl -OLf https://github.com/skycocker/chromebrew/raw/3f3f8d7008b32366a6248e729f1907cf008c82b9/packages/git.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177    0   177    0     0     34      0 --:--:--  0:00:05 --:--:--    40
Segmentation fault
```

### I expected the following
```curl-i386 -OLf https://github.com/skycocker/chromebrew/raw/3f3f8d7008b32366a6248e729f1907cf008c82b9/packages/git.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   177  100   177    0     0   1164      0 --:--:-- --:--:-- --:--:--  1164
100  2461  100  2461    0     0   7457      0 --:--:-- --:--:-- --:--:-- 19688
```
The working version is using musl: 
```
curl-i386 -V
curl 7.75.0 (x86_64-pc-linux-musl) libcurl/7.75.0 OpenSSL/1.1.1j zlib/1.2.11 libssh2/1.9.0 nghttp2/1.41.0
Release-Date: 2021-02-03
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

### curl/libcurl version
```
curl -V
curl 7.77.1-DEV (x86_64-cros-linux-gnu) libcurl/7.77.1-DEV OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.5.0 libidn2/2.3.1 libpsl/0.21.1 (+libidn2/2.3.1) nghttp2/1.43.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP TrackMemory UnixSockets zstd
```

### operating system

This is in a x86_64  ChromeOS M90 container with glibc 2.27.

gdb output:
```
chronos@cheekon-x86_64 /usr/local/tmp/crew $ gdb --args curl -OLf https://github.com/skycocker/chromebrew/raw/3f3f8d7008b32366a6248e729f1907cf008c82b9/packages/git.rb
GNU gdb (Chromebrew) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-cros-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from curl...
(gdb) run
Starting program: /usr/local/bin/curl -OLf https://github.com/skycocker/chromebrew/raw/3f3f8d7008b32366a6248e729f1907cf008c82b9/packages/git.rb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/local/lib64/libthread_db.so.1".
[New Thread 0x7f75a8e49700 (LWP 4062627)]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0[Thread 0x7f75a8e49700 (LWP 4062627) exited]
100   177  100   177    0     0     34      0  0:00:05  0:00:05 --:--:--    40
[New Thread 0x7f75a8e49700 (LWP 4062628)]

Thread 3 "curl" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f75a8e49700 (LWP 4062628)]
0x00007f75a863f414 in ?? () from /usr/local/lib64//libnss_files.so.2
(gdb) bt full
#0  0x00007f75a863f414 in ?? () from /usr/local/lib64//libnss_files.so.2
No symbol table info available.
#1  0x00007f75a8640728 in _nss_files_gethostbyname4_r () from /usr/local/lib64//libnss_files.so.2
No symbol table info available.
#2  0x00000000006f0c39 in gaih_inet (name=name@entry=0x1883788 "raw.githubusercontent.com", service=<optimized out>, req=req@entry=0x19a14e8, pai=pai@entry=0x7f75a8e48848, 
    naddrs=naddrs@entry=0x7f75a8e48844, tmpbuf=tmpbuf@entry=0x7f75a8e488b0) at ../sysdeps/posix/getaddrinfo.c:786
        fct4 = 0x7f75a8640670 <_nss_files_gethostbyname4_r>
        pat = 0x7f75a8e48678
        no_inet6_data = 0
        nip = 0x7f75a4001e20
        status = <optimized out>
        no_more = 0
        no_data = 0
        inet6_status = NSS_STATUS_UNAVAIL
        res_ctx = 0x18947a0
        res_enable_inet6 = <optimized out>
        tp = <optimized out>
        st = 0x7f75a8e485d0
        at = 0x7f75a8e48590
        got_ipv6 = false
        canon = 0x0
        orig_name = 0x1883788 "raw.githubusercontent.com"
        alloca_used = <optimized out>
        port = <optimized out>
        malloc_name = false
        addrmem = 0x0
        canonbuf = 0x0
        result = 0
#3  0x00000000006f1b41 in getaddrinfo (name=<optimized out>, service=<optimized out>, hints=0x19a14e8, pai=0x7f75a8e48d08) at ../sysdeps/posix/getaddrinfo.c:2300
        tmpbuf = {data = 0x7f75a8e488c0, length = 1024, __space = {__align = {__max_align_ll = 7146757915086711143, __max_align_ld = 1.71331743553534979715e-4939}, 
            __c = "github.com\000github.com", '\000' <repeats 11 times>, "\061\062\067.0.0.1\tlocalhost\n\000\066_64", '\000' <repeats 23 times>, "\356\210\344\250u\177\000\000\374\210\344\250u\177", '\000' <repeats 682 times>...}}
        i = 0
        last_i = 0
        nresults = 0
        p = 0x0
        gaih_service = {name = 0x7f75a8e48d2c "443", num = 443}
        pservice = <optimized out>
        local_hints = {ai_flags = 0, ai_family = 0, ai_socktype = 0, ai_protocol = 0, ai_addrlen = 0, ai_addr = 0x0, ai_canonname = 0x0, ai_next = 0x0}
        in6ai = 0x0
        in6ailen = 0
        seen_ipv4 = false
        seen_ipv6 = false
        check_pf_called = false
        end = 0x7f75a8e48848
        naddrs = 0
        __PRETTY_FUNCTION__ = "getaddrinfo"
#4  0x00000000007345ee in curl_dbg_getaddrinfo (hostname=0x7f75a8e488e1 "27.0.0.1\tlocalhost\n", service=0x7f75a8e48d2c "443", hints=0x31, result=0x7f75a8e48d08, line=130, 
    source=<optimized out>) at curl_addrinfo.c:560
        res = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
#5  Curl_getaddrinfo_ex (nodename=0x7f75a8e488e1 "27.0.0.1\tlocalhost\n", servname=0x7f75a8e48d2c "443", hints=0x31, result=0x19a14e0) at curl_addrinfo.c:130
        calast = 0x0
        cafirst = 0x0
        aihead = 0x7f75a4000020
        error = <optimized out>
        ai = <optimized out>
        ss_size = <optimized out>
        ca = <optimized out>
        namelen = <optimized out>
#6  getaddrinfo_thread (arg=0x19a14b0) at asyn-thread.c:306
        service = "443\000\240Es\000\000\000\000"
        buf = " "
        tsd = 0x19a14b0
        td = <optimized out>
        rc = <optimized out>
#7  0x00000000007349f7 in curl_thread_create_thunk (arg=<optimized out>) at curl_threads.c:57
        ac = <optimized out>
        func = <optimized out>
        real_arg = <optimized out>
#8  0x000000000065b437 in start_thread (arg=0x7f75a8e49700) at pthread_create.c:463
        pd = 0x7f75a8e49700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140143321454336, 100628543357974262, 140730101215838, 140730101215839, 140730101215840, 15, -31858445544196362, 
                100629416809592566}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#9  0x00000000006f4abb in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) 
```

**Comment by jay** [comment]
Are you able to reproduce this all of the time? Can you [bisect](https://github.com/curl/curl/wiki/how-to-git-bisect) it?

**Comment by satmandu** [comment]
This is reproducible, yes. I'm going to limit the compilation flags first and see if I get the same issue, and then bisect next.

**Comment by bagder** [comment]
I cannot reproduce on my debian linux.

**Comment by satmandu** [comment]
This might be a quirk with openssl & other libraries built with GCC, and
then trying to use that to build a static curl. I'll report back if this
remains an issue.

**Comment by satmandu** [comment]
I resolved this by building with musl. This must be an issue with the older glibc on these systems.
