### ISSUE TITLE
The mailing lists on lists.haxx.se are DOWN

### ISSUE THREAD

**Issue by bagder** [curl/curl#8073]
We're currently hard at work trying to get them back up. Maybe use [discussions](https://github.com/curl/curl/discussions) until then.

**Comment by bagder** [comment]
We upgraded the server to Debian 11, Bullseye.

They no longer ship Python 2 in this release and they no longer provide mailman v2. We used mailman 2 for our mailing lists.

The suggested upgrade path is to mailman 3. It is written to use python 3, but it is also not just an upgrade. Mailman 3 is a completely different beast than version 2 and the upgrade is, well, I'm not sure how to phrase it in a nice manner: it is a steep learning curve with complete inadequate tools for doing it automatically and next to stupid log lines when things go wrong.

I will get it done, but it will take me time so that I don't lose my mind in the process.

**Comment by bagder** [comment]
1. When I add the proposed lines to the postfix config, I can't send emails anymore.
2. mailman-web keeps saying it can't access the database, and shows a huge django stack trace dump **but doesn't say which file** it can't access.

`/var/log/mailman3/web/mailman-web.log` excerpt:
~~~
Traceback (most recent call last):
  File "/usr/share/mailman3-web/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django_q/management/commands/qcluster.py", line 21, in handle
    q = Cluster()
  File "/usr/lib/python3/dist-packages/django_q/cluster.py", line 40, in __init__
    self.broker = broker or get_broker()
  File "/usr/lib/python3/dist-packages/django_q/brokers/__init__.py", line 182, in get_broker
    return orm.ORM(list_key=list_key)
  File "/usr/lib/python3/dist-packages/django_q/brokers/__init__.py", line 10, in __init__
    self.connection = self.get_connection(list_key)
  File "/usr/lib/python3/dist-packages/django_q/brokers/orm.py", line 20, in get_connection
    if transaction.get_autocommit():  # Only True when not in an atomic block
  File "/usr/lib/python3/dist-packages/django/db/transaction.py", line 25, in get_autocommit
    return get_connection(using).get_autocommit()
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 379, in get_autocommit
    self.ensure_connection()
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py", line 194, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.OperationalError: unable to open database file
[uwsgi-daemons] respawning "python3 manage.py qcluster" (uid: 33 gid: 33)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/lib/python3/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3/dist-packages/django/db/backends/sqlite3/base.py", line 194, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

**Comment by bagder** [comment]
I'm now looking into building mailman2 completely from source as a stopgap measure to get the lists up again before I go crazy on this.

**Comment by toshywoshy** [comment]
I am not a MailMan expert and just giving my 2 cents.
I think Django isn't using your config correctly unless you're running on SQLite3, and if so, you'll need to set the data path in full for your sqlite3 path. The default I think is : /var/lib/mailman/sqlite.db
If you have PostgreSQL, MySQL or MariaDB running, you need to put your config in the right place, I think it changed from Mailman2 to Mailman3.

**Comment by bagder** [comment]
... and I think I have it specified in the right place.

This turned out to be a truly annoying experience. Next I'll build and install python2 + mailman2 from source and try to backpedal to get that up again, and postpone the work on mailman 3 to a future instead.

**Comment by DemiMarie** [comment]
> ... and I think I have it specified in the right place.
> 
> This turned out to be a truly annoying experience. Next I'll build and install python2 + mailman2 from source and try to backpedal to get that up again, and postpone the work on mailman 3 to a future instead.

Does Python 2 have any known vulnerabilities that are relevant here?

**Comment by toshywoshy** [comment]
I never migrated to MailMan3, in stead I moved to Discourse, as it has forum & mailinglist in one system.
While it isn't MailMan, many people prefer to live in a browser, however it still has a mailinglist mode and can be hooked up to chat systems to send out messages using webhooks.

**Comment by bagder** [comment]
A first email on the restored curl-library mailing list seems to have "gone through" now. I'll work on restoring everything else as well, like the web UI etc.

**Comment by bagder** [comment]
The web UI seems to be back and fine again too now. Fingers crossed.

**Comment by williamdes** [comment]
For anyone else finding this post as the only source for this access denied error.
Know that mailman-web needs the file access, and in my case it had to `chown -R www-data:www-data /var/lib/mailman3/web/`
Because in `/usr/bin/mailman-web` it does `su` as `www-data`
