### ISSUE TITLE
hostcache_timestamp_remove stack-buffer-overflow

### ISSUE THREAD

**Issue by ruslanbyku** [curl/curl#9786]
### Intoduction
I was fuzzing libcurl source code until the program I used found the **stack-buffer-overflow** error in the _hostcache_timestamp_remove_ function.

### Severity

low

### System information (where the bug has been found):
- Arch Linux x86_64 (5.19.12-arch1-1)
- libcurl (7.85.0)

Used tools:
- [FuzzTrigger](https://github.com/ruslanbyku/FuzzTrigger)
- clang (14.0.6)

### Steps to reproduce

```
#include <time.h>
#include <sys/socket.h>

#  define CURL_TYPEOF_CURL_SOCKLEN_T socklen_t

/* Data type definition of curl_socklen_t. */
#ifdef CURL_TYPEOF_CURL_SOCKLEN_T
  typedef CURL_TYPEOF_CURL_SOCKLEN_T curl_socklen_t;
#endif

struct Curl_addrinfo {
  int                   ai_flags;
  int                   ai_family;
  int                   ai_socktype;
  int                   ai_protocol;
  curl_socklen_t        ai_addrlen;   /* Follow rfc3493 struct addrinfo */
  char                 *ai_canonname;
  struct sockaddr      *ai_addr;
  struct Curl_addrinfo *ai_next;
};

struct Curl_dns_entry {
  struct Curl_addrinfo *addr;
  /* timestamp == 0 -- permanent CURLOPT_RESOLVE entry (doesn't time out) */
  time_t timestamp;
  /* use-counter, use Curl_resolv_unlock to release reference */
  long inuse;
};

struct hostcache_prune_data {
  long cache_timeout;
  time_t now;
};

static int
hostcache_timestamp_remove(void *datap, void *hc)
{
  struct hostcache_prune_data *data =
    (struct hostcache_prune_data *) datap;
  struct Curl_dns_entry *c = (struct Curl_dns_entry *) hc;

  return (0 != c->timestamp)
    && (data->now - c->timestamp >= data->cache_timeout);
}

int main(int argc, char** argv) {
    unsigned char bytes[] = {0x00};

    (void) hostcache_timestamp_remove(bytes, bytes);

    return 0;
}
```
If you compile the code above and run it:
```
$ clang -O0 -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-coverage=trace-cmp,trace-gep,trace-div hostcache_timestamp_remove_bug_reproduce.c -o bug_reproduce
$ ./bug_reproduce
```

```
=================================================================
==35341==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff0a934908 at pc 0x55b477391f96 bp 0x7fff0a934860 sp 0x7fff0a934858
READ of size 8 at 0x7fff0a934908 thread T0
    #0 0x55b477391f95 in hostcache_timestamp_remove $HOME/Desktop/libcurl/hostcache_timestamp_remove/hostcache_timestamp_remove_bug_reproduce.c:42:19
    #1 0x55b477391ed3 in main $HOME/Desktop/libcurl/hostcache_timestamp_remove/hostcache_timestamp_remove_bug_reproduce.c:49:12
    #2 0x7f742cd3428f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #3 0x7f742cd34349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #4 0x55b477299084 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

Address 0x7fff0a934908 is located in stack of thread T0 at offset 40 in frame
    #0 0x55b477391def in main $HOME/Desktop/libcurl/hostcache_timestamp_remove/hostcache_timestamp_remove_bug_reproduce.c:46

  This frame has 1 object(s):
    [32, 33) 'bytes' (line 47) <== Memory access at offset 40 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow $HOME/Desktop/libcurl/hostcache_timestamp_remove/hostcache_timestamp_remove_bug_reproduce.c:42:19 in hostcache_timestamp_remove
Shadow bytes around the buggy address:
  0x10006151e8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e8e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e910: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x10006151e920: 01[f3]f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006151e970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==35341==ABORTING
```

To be precise this line triggers the **buffer-over-read** bug.
```
return (0 != c->timestamp)
    && (data->now - c->timestamp >= data->cache_timeout);
```

If you find the provided information useful, then I would more than happy if you check my own tool [FuzzTrigger](https://github.com/ruslanbyku/FuzzTrigger) that found the bug out and place it a star.

**Comment by bagder** [comment]
This is not a bug. You're calling the function with incorrect (junk) inputs. It is not supposed to work like this.

**Comment by ruslanbyku** [comment]
What is junk to you? Is an empty string still junk?

```
char* data = "";
(void) hostcache_timestamp_remove(data, data);
```

Compiling the above code snippet still gives me buffer-overflow.

I can even do that:
`(void) hostcache_timestamp_remove(NULL, NULL);`

and it will give `SEGV on unknown address`.


The main idea behind this bug is that you do not even check parameters for not being NULL and just saying "It's not supposed to work this way".

**Comment by dfandrich** [comment]
Non-NULL inputs is a precondition, which, if not satisfied, will result in
unspecified results. Preconditions is a normal part of an API specification.
You'll find if you look at curl's source code that it's impossible for curl to
ever violate those preconditions (and if not, *that* is a bug).
