### ISSUE TITLE
Curl_hash_str division by zero and stack-buffer-overflow

### ISSUE THREAD

**Issue by ruslanbyku** [curl/curl#9788]
### Intoduction

I was fuzzing libcurl source code until the program I used found the stack-buffer-overflow error in the _Curl_hash_str_ function.

### Severity
low

### System information (where the bug has been found):
- Arch Linux x86_64 (5.19.12-arch1-1)
- libcurl (7.85.0)

Used tools:
-  [FuzzTrigger](https://github.com/ruslanbyku/FuzzTrigger)
- clang (14.0.6)

### Steps to reproduce
```
#include <stdint.h>
#include <string.h>

size_t Curl_hash_str(void *key, size_t key_length, size_t slots_num)
{
  const char *key_str = (const char *) key;
  const char *end = key_str + key_length;
  size_t h = 5381;

  while(key_str < end) {
    h += h << 5;
    h ^= *key_str++;
  }

  return (h % slots_num);
}

int main(int argc, char** argv) {
    unsigned char bytes[] = {0x00};
    //
    // 1 case - FPE on unknown address
    int64_t var_1 = 0;
    //
    // 2 case - stack-buffer-overflow on address
    //int64_t var_1 = 723401728380766730;

    (void) Curl_hash_str(bytes, var_1, var_1);

    return 0;
}
```

If you compile the code above and run it:
```
$ clang -O0 -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-coverage=trace-cmp,trace-gep,trace-div Curl_hash_str_bug_reproduce.c -o bug_reproduce
$ ./bug_reproduce
```
in the 1 case you will have (division by zero):
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==36309==ERROR: AddressSanitizer: FPE on unknown address 0x55cd84da6e8f (pc 0x55cd84da6e8f bp 0x7ffd51df2670 sp 0x7ffd51df2630 T0)
    #0 0x55cd84da6e8f in Curl_hash_str $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:15:13
    #1 0x55cd84da6fa0 in main $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:29:12
    #2 0x7f69a836b28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #3 0x7f69a836b349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #4 0x55cd84cae084 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:15:13 in Curl_hash_str
==36309==ABORTING
```

in the 2 case you will have (stack-buffer-overflow):
```
=================================================================
==36277==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffa3d465e1 at pc 0x55c62c55ee72 bp 0x7fffa3d46560 sp 0x7fffa3d46558
READ of size 1 at 0x7fffa3d465e1 thread T0
    #0 0x55c62c55ee71 in Curl_hash_str $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:12:10
    #1 0x55c62c55efa6 in main $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:29:12
    #2 0x7f919079928f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #3 0x7f9190799349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 26c81e7e05ebaf40bac3523b7d76be0cd71fad82)
    #4 0x55c62c466084 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

Address 0x7fffa3d465e1 is located in stack of thread T0 at offset 33 in frame
    #0 0x55c62c55eeaf in main $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:20

  This frame has 1 object(s):
    [32, 33) 'bytes' (line 21) <== Memory access at offset 33 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow $HOME/Desktop/libcurl/Curl_hash_str/Curl_hash_str_bug_reproduce.c:12:10 in Curl_hash_str
Shadow bytes around the buggy address:
  0x1000747a0c60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0c90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0ca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1000747a0cb0: 00 00 00 00 00 00 00 00 f1 f1 f1 f1[01]f3 f3 f3
  0x1000747a0cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000747a0d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==36277==ABORTING
```

I am not pretty sure about the severity of the 2 case as there is stack read and then wrapping its content in a hash string, however I presume that hashing with the djb2 algorithm is [irreversible](https://crypto.stackexchange.com/questions/18340/reversing-djb2-hashes).

If you find the provided information useful, then I would more than happy if you check my own tool [FuzzTrigger](https://github.com/ruslanbyku/FuzzTrigger) that found the bug out and place it a star.

**Comment by bagder** [comment]
This looks like garbage input to the function. That's blatant wrong use and the function is not written nor meant to be used like this. Not a bug.

**Comment by ruslanbyku** [comment]
1. It is enough for me to write the function call like this:
`(void) Curl_hash_str("", 0, 0);`

You do not even check `size_t slots_num` for not being **zero** and then you divide by zero:
`return (h % slots_num);`



2. It is enough for me to write the function call like this:
`(void) Curl_hash_str(NULL, 1, 0);`

and I will have the **Segmentation Fault** kind of error which means that you do not even check an input string for not being **NULL** and then dereference it.

**Comment by bagder** [comment]
> You do not even check size_t slots_num for not being zero

Right, because having a positive number is a pre-condition. This is an internal function, we don't have to protect it against random junk being passed it.

> It is enough for me to write the function call like this:

Yes, because passing in valid pointer in the first argument is a pre-condition.
